version: '3.7'
services:
  php8-sandbox:
    container_name: php8-sandbox
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PHP_IMAGE: 8.1.0RC4-apache-buster
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "8010:80"
    environment:
      - VIRTUAL_HOST=www.php8-sandbox.local
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_PID_FILE=/tmp/apache2.pid
      - APACHE_LOCK_DIR=/var/lock/apache2
    extra_hosts:
      - "www.php8-sandbox.local:127.0.0.1"
